spring.application.name=ConfigServer
server.port=8085


#Eureka Client Configuration
# It's important to set the prefer-ip-address to true, otherwise eureka will register the service with its hostname which might not be resolvable in some environments.
# This is especially important in containerized environments like Docker or Kubernetes where the hostname might not be easily resolvable.
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka/
